### ISSUE TITLE
Error when trying to export channel

### ISSUE THREAD

**Issue by limsammy** [hermit-crab/discord-export#1]
```
[E 181021 17:12:59] 'Guild' object has no attribute 'role_hierarchy'
    Traceback (most recent call last):
      File "/Users/sam/Library/Python/3.6/lib/python/site-packages/discord_export/cli.py", line 312, in main
        loop.run_until_complete(run(client, conf, creds))
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
        return future.result()
      File "/Users/sam/Library/Python/3.6/lib/python/site-packages/discord_export/cli.py", line 227, in run
        f.write(format_record('server_info', serialize_server(guild)))
      File "/Users/sam/Library/Python/3.6/lib/python/site-packages/discord_export/serialize.py", line 144, in serialize_server
        obj['roles'] = [serialize_role(e) for e in model.role_hierarchy]
    AttributeError: 'Guild' object has no attribute 'role_hierarchy'
```

**Comment by hermit-crab** [comment]
663cf28 should fix it, thank you for reporting
